### PR TITLE
Win lss

### PR DESCRIPTION
**Pull request by nebukadhezer**
Hey Ryan,

added an lss.bat for win, I only have windows 7 at hand.
Obviously python has to be in the PATH envvar in order to execute like this...

Cheers
Johannes

### CODE REVIEW

**Comment by nebukadhezer** [comment]
I guess I ll close this now?
cheers

**Comment by rsgalloway** [comment]
Hi Johannes, sorry for not responding. Is the universal_newlines meant to give better unicode support? For the .bat file, it's so simple I'm unsure of the value of including it in the repo. Seems like if a windows user needs that it would be trivial to write.

**Comment by nebukadhezer** [comment]
Hi,
When stdout or stderr are pipes and universal_newlines is True then all line endings will be converted to '\n' ....
this is from the docs, it is just to make sure the unittest is not failing.
sometimes newline would be '\r\n'...
And yes the bat is minimal and easily replicated.
Cheers

**Comment by rsgalloway** [comment]
If you submit a new PR for 56d694efc4d952d8761259daedd29613fb104ba6 I'll merge that.

**Pull request closed without merging**
