### PR TITLE
Lots of fixes/updates and also Python 3+ compatibility

### PR DESCRIPTION
**Pull request by eoyilmaz**
Hey Ryan,

It's been a while that I didn't touch the code. I've done quite a bit of update today to the code.

The changes include:

* **New:** Updated the code to support Python 3+

* **Update:** ``Sequence.length``, ``Sequence.frames``, ``Sequence.tail``,
  ``Sequence.head``, ``Sequence.start`` and ``Sequence.end`` are all read-only properties
  now instead of methods. So calling them will raise a ``TypeError``.

* **New:** Added *unittests* for the whole library.

* **Update:** The ``format`` parameter is renamed to ``fmt`` in
  ``uncompress()`` to not to shadow the **Python built-in**.

* **Update:** ``Item.isSibling()`` is renamed to ``Item.is_sibling`` to comply
  with PEP8.

* **Update:** Renamed ``getSequences()`` has been renamed to
  ``get_sequences()`` to comply with **PEP8**.

* **New:** Added a new method called ``can_contain()`` to ``Sequence`` class
  which does what the ``contains()`` method was doing in previous
  implementations, that is, it checks if the given item can be contained in
  one particular Sequence.

* **Update:** Updated ``Sequence.contains()`` method to do what it implies to
  to do, that is, it now checks if the item is inside the boundaries of the
  Sequence.

* **Fix:** The padding characters are now properly interpreted, as shown
  below::

```python
    seq = Sequence([
        'file.0001.jpg',
        'file.0002.jpg',
        'file.0003.jpg',
        'file.0006.jpg'
    ])

    print(seq.format('%h%04s-%04e%t'))
    # will print 'file.0001-0006.jpg'

    print(seq.format('%h%4s-%4e%t'))
    # will print 'file.   1-   6.jpg'
```

### CODE REVIEW

**Comment by rsgalloway** [comment]
Hey Erkan,

Awesome updates, thanks for the continued hard work. I think your clone might be missing a commit from a couple of weeks ago though. There is already a version 0.3.0, check it out:

https://github.com/rsgalloway/pyseq/commit/75b050232491e147681c298d9076a03becdce20d

Also, I wonder if it's a good idea to upgrade it to be 100% PEP8 compliant, specifically the method name changes. Also, the readonly properties vs. method changes. I'd hate to break the API for users. I'm thinking it should at least be backwards compatible. 

There are also some test files missing in your PR: 
```
   3 fileA.%04d.jpg 1-3
   3 fileA.%04d.png 1-3
```
When I lss these files with your clone it's not working:
```
   1 fileA.0001.jpg
   1 fileA.0001.png
   1 fileA.0002.jpg
   1 fileA.0002.png
   1 fileA.0003.jpg
   1 fileA.0003.png
```
Regardless, many of your updates are good. The unit tests are a great idea, and I want to merge that in. Also, the "can contain" vs. "contains" change is a good logical change.

**Comment by eoyilmaz** [comment]
Ok I've merged upstream and fixed conflicts.

Also I've reverted back the function names to the original to not to break backward compatibility. Updated a couple of tests and all are passing.

The only change left that is breaking the backward compatibility is the ``fmt`` argument in ``Sequence.format`` and ``uncompress``. If you want to keep them as ``format`` I can update the code.

**Comment by Narthe** [comment]
Hey guys ! i look forward for this pull request to be merged =P

**Comment by nebukadhezer** [comment]
Update: Sequence.length, Sequence.frames, Sequence.tail,
Sequence.head, Sequence.start and Sequence.end are all read-only properties
now instead of methods. So calling them will raise a TypeError.

Would be nice maybe to have a development branch for stuff like this so, people can adopt over time...
I know it is a bit more to maintain, but this way maybe at some stage the jump away from the methods can be made...

thumbs up for your work!! 

Cheers
johannes

**Comment by eoyilmaz** [comment]
@nebukadhezer they are all reverted back, so no changes in calling them, except for the **format** argument in ``Sequence.format`` and ``uncompress`` where it is now ``fmt`` and I'm waiting for Ryan's comment on that.

**Comment by nebukadhezer** [comment]
@eoyilmaz yep
I personally prefer to have those not as methods too, I thought having a separate branch for the "method"less side of things would be an option.

 And then at some stage one could merge the branches...

**Comment by rsgalloway** [comment]
Hey guys, sorry... been a bit busy with Alembic work lately. I will do my best to review this and #11 tonight and do some further testing. 

My understanding of PEP8 is that reserved word collision on methods/attributes/args are usually resolved by appending an underscore rather than an abbreviation or spelling corruption, format_ instead of fmt (not that either one of these is very ideal, maybe a new argument name would be better):

https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments
https://www.python.org/dev/peps/pep-0008/#designing-for-inheritance

Either way, I still don't think it's a good idea to break the API without an adequate amount of warning. There are a number of outstanding dev items as well, so maybe it makse sense to target some of these updates for a 0.4.0 branch which gets merged into master at some future date? Just a thought.

**Comment by rsgalloway** [comment]
Because of the changes to Sequence.contains, and Sequence.format and uncompress (which are noted in the CHANGELOG) I'm calling this 0.4.0. Hopefully, we won't need to worry about too many significant updates to the API that might break backwards compatibility, but anything like that are best done in a branch and should be weighed carefully.

In an effort to be a bit more egalitarian, I removed __author__. Contributors will be listed in the AUTHORS file only. For those who have contributed significant updates and feel like they want to take on a bit more responsibility for this library, then I can add them as github collaborators for this project. I hope that's fair.

Thanks again for the great updates!

**Pull request merged**
